---
- name: Install public signing key dnsdist
  apt_repository:
    repo: "{{ dnsdist_apt_repo }}"
    state: present

- name: Set up pdns preferences.d file
  template: src=templates/dnsdist.j2
            dest="{{ dnsdist_preferences }}"
            owner=root
            group=root
            mode=0775

- name: Add pdns repo key
  apt_key:
    url: "{{ pdns_repo_key }}"
    state: present

- name: Install dns-dist
  apt:
    pkg: dnsdist
    update_cache: yes
    state: present
  become: yes

- name: Stop dnsdist before update
  service:
    name: dnsdist
    state: stopped
  ignore_errors: yes
  become: yes

- include: configure-dnsdist.yml
