---
#This playbook is responsible for the ingestion of an initial import.

- hosts: master
  become: yes
  any_errors_fatal: true
  vars_files:
    - vars/vars.yml
  tasks:

#Obtain basic information about today's download/ingestion.

    - name: Fail check | for input variables
      fail: msg="Must provide a date 'dest_index' for which to to perform an import."
      when: dest_index is not defined

    - name: Ensure {{ history_directory }} directory exists
      file: path={{ history_directory }} state=directory

# check if main-history
    - name: Check if {{ dest_index }}.main-history file exists
      stat: path={{ history_directory }}/{{ dest_index }}.main-history
      register: historyFileExists

# if main-history file exists, parse that

    - name: Get last date recorded in {{ dest_index }}.main-history
      command: tail -n 1 {{ history_directory }}/{{ dest_index }}.main-history
      register: historyFileOutput
      when: historyFileExists.stat.exists == true

    - name: Obtain next_day_to_ingest date
      shell: date -d "{{ historyFileOutput.stdout }} + 1 day" +%Y-%m-%d
      register: next_day_to_ingest
      when: historyFileExists.stat.exists == true

    - name: Set variable | next_day_to_ingest_stdout
      set_fact: start_ingestion_date="{{ next_day_to_ingest.stdout }}"
      when: historyFileExists.stat.exists == true

    - name: Obtain todays_date date
      shell: date +%Y-%m-%d
      register: todays_date
      when: historyFileExists.stat.exists == true

    # Script Usage: node <script_path> <start_date> <end_date>
    - name: Run script to gather list of dates from {{ start_ingestion_date }} up through {{ todays_date.stdout }}
      shell: node {{ print_dates_in_range_script_path }} {{ start_ingestion_date }} {{ todays_date.stdout }}
      register: datesOutput
      when: historyFileExists.stat.exists == true

    - name: Set variable | list_of_dates
      set_fact: list_of_dates={{ datesOutput.stdout_lines }}
      when: historyFileExists.stat.exists == true

# else, parse dates in folder

    - name: Obtain list of dates.
      shell: ls {{ zone_downloads_directory }} | cut -f 1
      register: datesOutput
      when: historyFileExists.stat.exists == false

    - name: Set variable | list_of_dates
      set_fact: list_of_dates={{ datesOutput.stdout_lines }}
      when: historyFileExists.stat.exists == false

    # - name: Set variable | es_master_ip
    #   # set_fact: es_master_ip="{{ hostvars[groups['es_master'][0]]['ansible_eth0']['ipv4']['address'] }}"
    #   set_fact: es_master_ip="192.168.1.165"

    # - name: Get new alias name
    #   shell: 'python3 /home/ubuntu/scripts/timestamp.py http://{{ es_master_ip }}:9200/*/_alias/{{ dest_index }} {{ dest_index }}'
    #   register: alias_name

    # - name: Set alias name
    #   set_fact: alias={{ alias_name.stdout_lines[0] }}

    # - name: Create Elasticsearch index
    #   uri:
    #     url: http://{{ es_master_ip }}:9200/{{ alias }}/
    #     method: PUT
    #     body: "{{ lookup('template', 'templates/zoneIndexMapping.json.j2') }}"
    #     body_format: json

    # - name: Set new alias
    #   shell: 'python3 /home/ubuntu/scripts/alias.py http://{{ es_master_ip }}:9200/*/_alias/{{ dest_index }} http://{{ es_master_ip }}:9200/_aliases {{ dest_index }} {{ alias }}'
    #   # shell: 'python3 /home/ubuntu/scripts/alias.py {{ es_master_ip }} {{ dest_index }} {{ alias }}'
    #   register: attempt

    # - name: Set attempt
    #   set_fact: num_attempt={{ attempt.stdout_lines[0] }}

    # - name: set set
    #   vars:
    #     current_index = {{ alias }}


    # - name: Set current index
    #   set_fact: current_index={{ alias }}

    # - debug: var=current_index

    # - name: Set variables | initial_logstash_config_directory
    #   set_fact: initial_logstash_config_directory="/etc/{{ logstash_initial_service }}/conf.d"

    # - debug: var=initial_logstash_config_directory

    # - name: Set variables | delta_logstash_config_directory
    #   set_fact: delta_logstash_config_directory="/etc/{{ logstash_delta_service }}/conf.d"

    # - debug: var=delta_logstash_config_directory

    # - name: Update Logstash Configuration for intial import
    #   template: src=templates/formatted-initial-import.conf.j2
    #             dest={{ initial_logstash_config_directory }}/formatted-initial-import.conf
    #             owner={{ logstash_user }}
    #             group={{ logstash_user }}
    #             mode=0644

    # - name: Update Logstash Configuration for delta update
    #   template: src=templates/formatted-delta-update.conf.j2
    #             dest={{ delta_logstash_config_directory }}/formatted-delta-update.conf
    #             owner={{ logstash_user }}
    #             group={{ logstash_user }}
    #             mode=0644


#Verify that directories needed for ingestion exist.

    - include: zone_ingestion_intermediate.yml
      with_items:
        - "{{ list_of_dates | default([]) }}"
      ignore_errors: yes
      loop_control:
        loop_var: outer_item

    # - name: Set new alias
    #   shell: 'python3 /home/ubuntu/scripts/delete_alias.py http://{{ es_master_ip }}:9200/*/_alias/{{ dest_index }} http://{{ es_master_ip }}:9200/_aliases {{ dest_index }} {{ alias }}'
    #   # shell: 'python3 /home/ubuntu/scripts/alias.py {{ es_master_ip }} {{ dest_index }} {{ alias }}'
    #   when: num_attempt == "2"
