---

- name: xpack | Uninstall xpack
  become: yes
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack
  args:
    chdir: "{{ elasticsearch_home_dir }}"
  notify: Restart Elasticsearch
  ignore_errors: yes

- name: xpack | Install xpack
  become: yes
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
  args:
    chdir: "{{ elasticsearch_home_dir }}"
  notify: Restart Elasticsearch
